---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo = TRUE}
act_data <- read.csv("C:/Users/sumim/OneDrive/ドキュメント/Coursera datascience/Reproduciable Research/activity.csv")

str(act_data)
```

```{r, echo = TRUE}
library(dplyr)
library(ggplot2)
```

## What is mean total number of steps taken per day?

```{r, echo = TRUE}
tsteps_perday <- act_data %>%
  na.omit() %>%
  group_by(date) %>%
  summarize(total_steps = sum(steps))

head(tsteps_perday)
```

```{r, echo = TRUE}
ggplot(tsteps_perday, aes(x= total_steps)) +
  geom_histogram(binwidth = 1000, fill="blue", color="black") +
  labs(title = "histgram of Total Steps per Day", x = "Total steps", y = "Count") +
 theme_minimal()
```

```{r, echo = TRUE}
mean_steps <- mean(tsteps_perday$total_steps)
median_steps <- median(tsteps_perday$total_steps)

mean_steps
median_steps
```

## What is the average daily activity pattern?

```{r, echo = TRUE}
avsteps_perint <- act_data %>%
  na.omit() %>%
  group_by(interval) %>%
  summarize(av_steps = mean(steps))

str(avsteps_perint)
```

```{r, echo = TRUE}
ggplot(avsteps_perint, aes(x = interval, y = av_steps)) +
  geom_line(color = "blue") +
  labs(title = "Average per interval", x = "5 minute interval", y = "Average steps")
```

```{r, echo = TRUE}
maxsteps_int <- avsteps_perint$interval[which.max(avsteps_perint$av_steps)]
maxsteps_int
```

## Imputing missing values

```{r, echo = TRUE}
sum(is.na(act_data$steps))
```

```{r, echo = TRUE}
act_data_naimputed <- act_data %>%
left_join(avsteps_perint, by = "interval") %>%
  mutate(steps = ifelse(is.na(steps), av_steps, steps)) %>%
  select(-av_steps)

str(act_data_naimputed)
```

```{r, echo = TRUE}
tsteps_perday2 <- act_data_naimputed %>%
  na.omit() %>%
  group_by(interval) %>%
  summarize(total_steps2 = sum(steps))

head(tsteps_perday2)
```

```{r}
ggplot(tsteps_perday2, aes(x= total_steps2)) +
  geom_histogram(binwidth = 1000, fill="blue", color="black") +
  labs(title = "histgram of Total Steps per Day", x = "Total steps new", y = "Count") +
 theme_minimal()
```

```{r, echo = TRUE}
mean_steps2 <- mean(tsteps_perday2$total_steps2)
median_steps2 <- median(tsteps_perday2$total_steps2)

mean_steps2
median_steps2
```

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}
act_data_naimputed$date <- as.Date(act_data_naimputed$date)
act_data_naimputed$date <- ifelse(weekdays(act_data_naimputed$date) %in% c("Saturday", "Sunday"), "Weekend", "Weekday")

str(act_data_naimputed)
```

```{r, echo = TRUE}
avsteps_perint_week <- act_data_naimputed %>%
  group_by(interval, date) %>%
  summarize(av_steps_week = mean(steps))

head(avsteps_perint_week)
```

```{r, echo = TRUE}
ggplot(avsteps_perint_week, aes(x = interval, y = av_steps_week, color = date)) +
  geom_line() +
  labs(title = "Average per interval weekday vs weekend", x = "5 minute interval", y = "Average steps") +
  scale_color_manual(values = c("Weekday" = "blue", "Weekend" = "red"))
```